### PR TITLE
Fixes problem with incorrect arguments passed to constructors #80

### LINKED ISSUE #80: QueuedMailDelivery nor DirectMailDelivery do not accept transaction_manager keyword
As per title currently including (via `config.include('pyramid_mailer'`) pyramid_mailer breaks my application with:

>   File "/home/ergo/Private/workspace/ziggurat_cms/backend/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 800, in include
>     c(configurator)
>   File "/home/ergo/Private/workspace/pyramid_mailer/pyramid_mailer/__init__.py", line 22, in includeme
>     mailer = mailer_factory_from_settings(settings, prefix=prefix)
>   File "/home/ergo/Private/workspace/pyramid_mailer/pyramid_mailer/__init__.py", line 11, in mailer_factory_from_settings
>     return Mailer.from_settings(settings, prefix)
>   File "/home/ergo/Private/workspace/pyramid_mailer/pyramid_mailer/mailer.py", line 281, in from_settings
>     return cls(username=username, password=password, **kwargs)
>   File "/home/ergo/Private/workspace/pyramid_mailer/pyramid_mailer/mailer.py", line 226, in __init__
>     self.smtp_mailer, transaction_manager=transaction_manager)
> TypeError: __init__() got an unexpected keyword argument 'transaction_manager'

### PR DESCRIPTION
**Pull request by ergo**
This fixes #80 problem.

### CODE REVIEW

**Comment by mmerickel** [comment]
The issue is (more than likely) that you are pinned to repoze.sendmail 4.1 which does not support this feature, however 4.2 does. I think you should instead lobby for a release to repoze.sendmail for whatever bug you are worried about, or you should pin pyramid_mailer as well.

**Comment by papachoco** [comment]
I monkey-patched repoze-sendmail since it has been more than a year since we have had a release of that package

**Comment by tseaver** [comment]
https://github.com/repoze/repoze.sendmail/pull/38

**Comment by ergo** [comment]
Indeed , closing this for now.

**Pull request closed without merging**
