### PR TITLE
`DebugMailer` optionally include bcc information on send

### PR DESCRIPTION
**Pull request by RaHus**
issue #86

### CODE REVIEW

**Comment by mmerickel** [comment]
I'm inclined to say that the `DebugMailer` should just always output the Bcc header instead of adding an option. If you feel strongly about keeping the option then I might say it should default to true. My perspective is that the `DebugMailer` is a very simple object for debugging and thus does not warrant exposing a full-blown config option in the library. I wonder what @tseaver thinks.

**Comment by mmerickel** [comment]
Awesome I hit the merge button on accident instead of submitting my comment... who does that?

**Comment by mmerickel** [comment]
I guess followup fixes will either be done by me or you'll have to add them in another PR.

**Comment by RaHus** [comment]
I would also agree that it makes sense for `DebugMailer` to output the Bcc data by default. 
About removing the option we should probably clean the extra_headers before returning from `_send` in case people are processing the message object after sending it?. 
I'll keep an eye in this thread for any suggestions for fixes and follow up with a PR

**Comment by tseaver** [comment]
Except for the fact that there is *no such thing* as a "Bcc:" header:  the whole point of "Bcc" is that it does *not* leave any trace in the message payload.  ISTM that expecting to find it there means that you are debugging the app at the wrong point:  write a unit test instead of staring at the chicken bones.

**Comment by RaHus** [comment]
just to make sure we are on the same page, the above implies that the option should be removed?

**Comment by tseaver** [comment]
@RaHus No, I mean that I prefer that it remain defaulted to `False`, as in this PR.

**Pull request merged**
