### PR TITLE
Fix lone \n in email as against RFC2822 recommendation

### PR DESCRIPTION
**Pull request by miohtama**
Otherwise sparkpost.com rejects outbound emails from us

### CODE REVIEW

**Comment by mmerickel** [comment]
@miohtama the tests are broken, it looks like you're depending on py3 changes to the email module

**Comment by bertjwregeer** [comment]
Sparkpost apparently failed to follow Postel's law:

> an implementation should be conservative in its sending behavior, and liberal in its receiving behavior
- Jon Postel (RFC 760)

Was later reworded to the one more people will be familiar with:

> Be liberal in what you accept, and conservative in what you send
- Reworded Jon Postel (RFC 1122)

It is an issue we should fix, but I wonder if it should be fixed in the Python standard library if that is where the error ultimately lies.

**Comment by ztane** [comment]
Ok seriously this should be fixed. We found out that if you use outlook365 SMTP as the outbound mailer, it will break on quopri bodies in an *evil fashion* if you use only `\n` instead of `\r\n`!

**Comment by ztane** [comment]
Related https://stackoverflow.com/questions/54292462/pyramid-mailer-message-and-content-transfer-encoding - all seem to be connected to the same issue.

**Comment by ztane** [comment]
Also https://bugs.python.org/issue724459

**Comment by ztane** [comment]
https://github.com/Pylons/pyramid_mailer/pull/95/

**Pull request merged**
