### PR TITLE
Coverting debug and port values in Mailer.from_settings #67

### PR DESCRIPTION
**Pull request by marioidival**
In tests, This problem don't appear...

### CODE REVIEW

**Comment by mmerickel** [comment]
Could you add a test that passes in a string to demonstrate the problem you're fixing?

**Comment by marioidival** [comment]
Of course @mmerickel

**Comment by mmerickel** [comment]
For example you could simply update the current test to use a string, as the assertion down below is ensuring it is an int value of 1.

https://github.com/Pylons/pyramid_mailer/blob/master/pyramid_mailer/tests/test_mailer.py#L190

**Comment by marioidival** [comment]
@marcinkuzminski  done :+1:

**Comment by mmerickel** [comment]
Looks good, can you please sign the contributors.txt file?

**Comment by mmerickel** [comment]
Thank you.

**Pull request merged**
